services:
  api:
    build: .
    ports:
      - "8000:8000"
  streamlit:
    build: .
    command: streamlit run app/streamlit_app.py --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
